// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXhCGFuvRYPiClz0kzU5mvkOUMgkaLRkw',
    appId: '1:21045562493:web:6a966b82f61c8d3f1d7514',
    messagingSenderId: '21045562493',
    projectId: 'instagramclone-53638',
    authDomain: 'instagramclone-53638.firebaseapp.com',
    storageBucket: 'instagramclone-53638.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJpn2yehPuQBMZ2YOZmsbcaT2nhQXeZ1c',
    appId: '1:21045562493:android:b3f549d6acebcc111d7514',
    messagingSenderId: '21045562493',
    projectId: 'instagramclone-53638',
    storageBucket: 'instagramclone-53638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_4r5Ck9HpP7butrlsAwhL7PM2uc0mjM0',
    appId: '1:21045562493:ios:0fe8b5730322de481d7514',
    messagingSenderId: '21045562493',
    projectId: 'instagramclone-53638',
    storageBucket: 'instagramclone-53638.appspot.com',
    iosClientId: '21045562493-38ccaoqetqh2p3o1bj047gkutk52g2e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
